# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gb4sVAikNYnlRrOZJ8LXJ6zk2ASr-aVP
"""

import streamlit as st
import pickle
import numpy as np
from urllib.parse import urlparse
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier


with open('rf_model7_features.pkl', 'rb') as file:
    model = pickle.load(file)

with open('rf_scalar7_features.pkl', 'rb') as file:
    ss2 = pickle.load(file)

st.title('URL prediction')
st.write("Enter the features below:")


feature1 = st.text_input('URL')

parsed = urlparse(feature1)
hostname = parsed.hostname

if feature1 is not None and hostname is not None:
    features = np.array([[len(feature1),
                          len(hostname),
                          feature1.count('www'),
                          feature1.count("/"),
                          feature1.count("-"),
                          feature1.count(".")]])
else:
    features = np.array([[len(feature1),
                          0,
                          feature1.count('www'),
                          feature1.count("/"),
                          feature1.count("-"),
                          feature1.count(".")]])

scaled_features = ss2.transform(features)
pred = model.predict(scaled_features)[0]
if pred == 1:
  output = "Phishing"
elif pred == 0:
  output = "Legitimate"
else:
  putput = "Unknown"

if st.button("Predict"):
    print(putput)




